<a href="https://colab.research.google.com/github/Avishek2020/ineuron_py12/blob/master/Session3_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Task1

####1 Write a function to compute 5/0 and use try/except to catch the exceptions.


In [80]:
def divide(a,b):
    res = a/b
    return res

a = 5
b= int(input())
try:
    result = divide(a,b)
except ZeroDivisionError:
    print("You can't divide by zero!")
except ValueError:
    print("invalid value")
else:
    print("result is "+ str(result))


5
result is 1.0


Output

####2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
```
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
```
**Output should come as below:**
```
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

```





In [0]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

##### Using For Loop

In [0]:
 forList =[]
 for subject in subjects:
     for verb in verbs:
         for object in objects:
             #print(f"{subject} {verb} {object}")
             forList.append(subject+" "+verb+" "+object)             

In [103]:
print("output :-   \n" )
forList

output :-   



['Americans  play Baseball',
 'Americans  play Cricket',
 'Americans  watch Baseball',
 'Americans  watch Cricket',
 'Indians play Baseball',
 'Indians play Cricket',
 'Indians watch Baseball',
 'Indians watch Cricket']

##### Using List Comprehension

In [0]:
mylist = [([([([subject+" " + verb +" "+object]) for subject in subjects]) for verb in verbs]) for object in objects]

Output

In [61]:
print("output :-   \n" )
mylist

output :-   



[[[['Americans  play Baseball'], ['Indians play Baseball']],
  [['Americans  watch Baseball'], ['Indians watch Baseball']]],
 [[['Americans  play Cricket'], ['Indians play Cricket']],
  [['Americans  watch Cricket'], ['Indians watch Cricket']]]]

##Task 2:

#### 1 Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

 
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

**NOTE: The solution shared through Github should contain the source code used and the
screenshot of the output.**  


In [0]:
def vaderMatrix(Inarr,n, boolArg):
    if boolArg:
        resMatx = np.array([j**i for j in Inarr for i in range(n)]).reshape(Inarr.size,n)
    elif not boolArg:
        resMatx = np.array([j**(n-i-1) for j in Inarr for i in range(n)]).reshape(Inarr.size,n)
    return resMatx

#### Output

In [20]:
x = np.array([1,2,3,4,5])
n = 3
boolArg = True
Vmatrix = vaderMatrix(Inarr,n, boolArg)
print("Matrix \n",Vmatrix)
 

Matrix 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


In [21]:
x = np.array([1,2,3,4,5])
n = 3
boolArg = False
Vmatrix = vaderMatrix(Inarr,n, boolArg)
print("Matrix \n",Vmatrix)

Matrix 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
